config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :plays do
    get "bookmarks/toggle"
    resources :reviews
  end
  root 'plays#index'
  resources :bookmarks, only: [:index]
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :play
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plays
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  belongs_to :user
  belongs_to :play
end

app/models/play.rb
class Play < ActiveRecord::Base
  has_many :bookmarks, :dependent => :destroy
  has_many :users, through: :clips
  belongs_to :category
  has_many :reviews



  validates :title, presence: true
  validates :description, presence: true
  validates :director, presence: true
  validates :image, presence: true
  validates :category_id, presence: true


  has_attached_file :play_img, :styles => { :play_index => "250x350>", :play_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :play_img, :content_type => /\Aimage\/.*\Z/
  mount_uploader :image, PictureUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :play
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookmarks
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def toggle
    play_id = params[:play_id]
    user_bookmarks = current_user.bookmarks
    if user_bookmarks.exists?(play: play_id)
      user_bookmarks.where(play: play_id).destroy_all
    else
      user_bookmarks.create(user: current_user, play: Play.find(play_id))
    end
    redirect_to root_path
  end

  def index
    @user = current_user
    @bookmarks = Bookmark.where(user_id: @user.id).all
  end

end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def create
    @user_id = current_user.id
    @play_id = @play_id
    @clip = Clip.new(clip_params)
    @clip.play_id = @play_id
    @clip.user_id = @user_id
        redirect_to root_path
  end

  def destroy
    @clip = Clip.find(params[:id])
    if @clip.destroy
      redirect_to user_path(current_user)
    end
  end

  private

  def clip_params
    params.require(:clip).permit(:play_id, :user_id)
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order("created_at DESC").page(params[:page]).per(8)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(:category_id => @category_id).order("created_at DESC").page(params[:page]).per(8)
    end
  end

  # def show
  #   if @play.reviews.blank?
  #     @average_review = 0
  #   else
  #     @average_review = @play.reviews.average(:rating).round(2)
  #   end
  # end

  def show
    @bookmarks = @play.bookmarks.all if @play.bookmarks.exists
    @bookmark = Bookmark.where(user_id: current_user, play_id: @play.id)
    @reviews = @play.reviews.order("created_at DESC")
    unless @reviews.present?
      @average_review = 0
    else
      @average_review = @reviews.average(:rating).present? ? @reviews.average(:rating).round(2) : 0
    end
  end


 #Example
  # def show
  #   @reviews =  @movie.reviews.order("created_at DESC")
  #   unless @reviews.present?
  #    @avg_review = 0
  #   else
  #    @avg_review = @reviews.average(:rating).present? ? @reviews.average(:rating).round(2) : 0
  #   end
  # end


  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]

    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:image, :title, :description, :director, :category_id, :play_img, :image_cache)
  end

  def find_play
    @play = Play.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_play
    @play = Play.find(params[:play_id])
  end

  def find_review
    @review =Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def bookmark_icon(play, user)
    if user
      if user.bookmarks.exists?(play: play)
        '<i class="fa fa-bookmark fa-2x"></i>'
      else
        '<i class="fa fa-bookmark fa-bookmark-o fa-2x"></i>'
      end
    end
  end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/index.html.erb
<div class="bookmark-index">
  <% if @bookmarks.count == 0 %>
    <h3>お気に入り映画がありません</h3>
  <% else %>
    <h3>お気に入り映画</h3>
    <% @bookmarks.each do |bookmark| %>
      <% play = Play.find(bookmark.play_id) %>
       <div class="col-md-3">
          <a href="/plays/ <%= play.id %>">
            <div class="image-index"><td><%= image_tag play.image.to_s %></td></div>
          </a>
       </div>
    <% end -%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "movie-demo", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "サインアップ", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end -%>
      </ul>

      <ul class="nav navbar-nav" %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ジャンル <span class="caret"></span></a>

          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, plays_path(category: category.name), class: "link" %>
              </li>
            <% end -%>
          </ul>

        <% if user_signed_in? %>
          <li><%= link_to "映画を登録する", new_play_path %></li>
          <li><%= link_to "お気に入り映画", bookmarks_path %></li>
        <% end -%>
      </ul>
    </div>
  </nav>

  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/plays/_form.html.erb
<% if @play.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @play.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @play, html: {multipart: true} do |f| %>
  <div class="form-group">
    <%if @play.image? %>
      画像は登録されました
      <%= f.hidden_field :image_cache %>
    <% else %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    <% end -%>
  <br>
  </div>

  <% if @play.category_id? %>
    ジャンルは登録されました
    <%= hidden_field_tag :category_id, @play.category_id %>
  <% else %>
    <%= select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :name), include_blank: "ジャンル選択") %>

  <% end -%>
  <%= f.input :title, label: "映画タイトル" %>
  <%= f.input :description, label: "映画あらすじ" %>
  <%= f.input :director, label: "映画監督" %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/plays/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>Edit Broadway Play</h1>

    <%= simple_form_for @play, html: {multipart: true} do |f| %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %><br>
      <%= f.select :category_id, @categories %><br>
      <%= f.input :title, label: "映画タイトル" %>
      <%= f.input :description, label: "映画あらすじ" %>
      <%= f.input :director, label: "映画監督" %>
      <%= f.submit "投稿する" %>
    <% end %>
  </div>
</div>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
  <h3>このジャンルの映画はありません</h3>
<% else %>
  <div class="row">
    <% @plays.each do |play| %>
      <div class="col-md-3">
        <a href="/plays/ <%= play.id %>">
          <div class="image-index"><td><%= image_tag play.image.to_s %></td></div>
        </a>
      </div>
    <% end -%>

  </div>
<% end -%>
<%= paginate(@plays) %>

app/views/plays/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>新しい映画を登録する</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/plays/show.html.erb
<div class="row">
  <div class="col-md-4">
    <td><%= image_tag @play.image.url(:thumb).to_s %></td>
  </div>

  <div class="col-md-8">
    <div class="play-info">
      <% if user_signed_in? %>
       <p>
          <%= link_to play_bookmarks_toggle_path(@play) , id: 'bookmark-link', data: { no_turbolink: true }, remote: true do %>
              <%=raw bookmark_icon(@play, current_user) %>
              <% if @bookmark.exists? %>
                お気に入り済み
               <% else %>
                お気に入りしますか？
              <% end -%>
          <% end %>
        </p>
      <% end -%>


      <h2 class="playy-title"><%= @play.title %></h2>
      <h3 class="play-director"><span>  監督: </span><%= @play.director %>  </h3>
      <h4 class="play-category">ジャンル：  <%= @play.category.name %></h4>
      <h4 class="avg-rating">平均レビュー</h4>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews"><em> 合計 </em><%= @play.reviews.count %> レビュー </span>
      <p class="play-descs"><br>あらすじ<br> <%= @play.description %></p>
    </div>
  </div>

  <div>

    

      </div>

</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1> レビュー </h1>
        <%= render @play.reviews %>
        <div>
          <%= link_to "レビューを登録する", new_play_review_path(@play), class: "btn-custom" %>
        </div>
    </div>
  </div>
</div>

<div class="links-fix">
  <div class="links btn-group">
    <% if user_signed_in? %>
      <% if @play.user_id == current_user.id %>
        <%= link_to "映画編集", edit_play_path(@play), class: "btn btn-custom" %>
        <%= link_to "映画削除", play_path(@play), method: :delete, data: { confirm: "本当に削除していいですか?" }, class: "btn btn-custom" %>
      <% end -%>
    <% end -%>
  </div>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>


<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |f| %>
  <div id="rating-form">
    <label> 評価 </label>
  </div>
  <%= f.input :comment, label: "コメント" %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>


<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group" %>
        <%= link_to "編集", edit_play_review_path(review.play, review), class: "btn btn-custom" %>
        <%= link_to "削除", play_review_path(review.play, review), method: :delete, data: { confirm: "本当に削除していいですか?" }, class: "btn btn-custom" %>
      </div>
    <% end -%>
  <% end -%>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1> レビュー編集 </h1>
      <%= simple_form_for([@play, @review]) do |f| %>
        <div id="rating-form">
          <label> レビュー </label>
        </div>
        <%= f.input :comment, label: "コメント" %>
        <%= f.button :submit, :class => "btn-custom2" %>
      <% end %>
  </div>
</div>


<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1>レビューを登録する</h1>
    <%= render 'form' %>
  </div>
</div>